package:
  name: cptcore
  version: "2.0.0"

source:
  path: ..

build:
  number: 0
  noarch: python 

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - cptio
    - psutil


test:
  imports:
    - cptcore
    - cptcore.functional
    - cptcore.tests

about:
  home: https://github.com/iri-pycpt/
  license: MIT
  summary: 'IRIs Climate Predictability Tool' 
  description: 'Somewhat like CPT'
  dev_url: https://github.com/iri-pycpt/
