package:
  name: cptcore
  version: "1.0.6"

source:
  path: ../src

build:
  number: 0
  string: cptcore
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - cptio
    - psutil
    - make # [linux]
    - fortran-compiler # [linux]
    - cxx-compiler # [linux]
    - libpng # [linux]
    - libgd # [linux]
    - jpeg # [linux]
    - libnetcdf # [linux]
    - openlibm # [linux]
    - xorg-libx11 # [linux]

test:
  imports:
    - cptcore
    - cptcore.functional
    - cptcore.tests

about:
  home: https://github.com/kjhall-iri/
  license: MIT
  summary: 'IRIs Climate Predictability Tool' 
  description: 'Somewhat like CPT'
  dev_url: https://github.com/kjhall-iri/
